### ISSUE TITLE
Showcase is down

### ISSUE THREAD

**Issue by hermanbarrantes** [adminfaces/site#3]
The [Showcase](https://adminfaces.github.io/admin-showcase/) is offline, show:

> Application is not available
> 
> The application is currently not serving requests at this endpoint. It may not have been started or is still starting.

In my case it redirects to [Showcase](https://adminfaces-adminfaces.apps.ca-central-1.starter.openshift-online.com/)

**Comment by rmpestano** [comment]
Yea, it should redirect to the new address (it is working for me at least): https://adminfaces-adminfaces.apps.us-east-1.starter.openshift-online.com/

**Comment by hermanbarrantes** [comment]
Thanks, the new link works well
